### ISSUE TITLE
pub_sub examples produce empty CSV files

### ISSUE THREAD

**Issue by calvinyy-oss** [irobot-ros/ros2-performance#100]
I can now bash  some .sh file,and get some results--csv file.But these files are empty
![图片](https://user-images.githubusercontent.com/75769276/162020254-11edcdf6-85e5-4dc2-8862-fc0c669e3a48.png)
![图片](https://user-images.githubusercontent.com/75769276/162020314-607449fc-2509-456e-8998-e0b8d4afc253.png)
![图片](https://user-images.githubusercontent.com/75769276/162020396-19d4eaec-de89-40bb-b12d-bc3d461157df.png)
![图片](https://user-images.githubusercontent.com/75769276/162020432-8b013aa0-3231-492e-9a27-1ff06d95df16.png)
I cant get a plot by using python3

**Comment by calvinyy-oss** [comment]
![图片](https://user-images.githubusercontent.com/75769276/162047148-8038aa10-bf26-4aca-85d0-4fcf06d93d26.png)
I thought the error is that Warning. Nothing parsed from .csv file

**Comment by calvinyy-oss** [comment]
![图片](https://user-images.githubusercontent.com/75769276/162058149-0de2a976-95f0-492f-b743-aef4a1243f46.png)
I read this .py file.I find this error shows.But I am not still understand why this waring shows

**Comment by calvinyy-oss** [comment]
![图片](https://user-images.githubusercontent.com/75769276/162064374-92e88534-2b50-4929-a20f-7fb78cef217e.png)
events .csv just like this

**Comment by alsora** [comment]
The files are obviously empty because the script that generates them is crashing with a segmentation fault.
This was clearly indicated in your previous "screenshot" https://github.com/irobot-ros/ros2-performance/issues/98#issuecomment-1089150572 (and please, don't post screenshots of terminals, why not copy-pasting the text??).

I fixed it in the latest commit https://github.com/irobot-ros/ros2-performance/commit/5b9c2f1b4267775408eb7222ab107ddaf484c6bc

**Comment by calvinyy-oss** [comment]
Thank you!There is a error:When run:python scripts/plot_scripts/cpu_ram_plot.py <path_to_experiments> --x msg_type --y cpu --separator send_frequency --skip 5
it shows:  File "scripts/plot_scripts/cpu_ram_plot.py", line 56, in parse_csv
    time = int(row_dict['time[ms]'])
KeyError: 'time[ms]

**Comment by calvinyy-oss** [comment]
Full error is:Traceback (most recent call last):
  File "scripts/plot_scripts/cpu_ram_plot.py", line 209, in <module>
    main(sys.argv[1:])
  File "scripts/plot_scripts/cpu_ram_plot.py", line 182, in main
    parsed_csv = parse_csv(file_path, skip)
  File "scripts/plot_scripts/cpu_ram_plot.py", line 56, in parse_csv
    time = int(row_dict['time[ms]'])
KeyError: 'time[ms]'

**Comment by alsora** [comment]
That's not a problem with the python scripts.
Please open a separate ticket showing the commands that you run for generating the csv files.
