### ISSUE TITLE
master     compilation failed

### ISSUE THREAD

**Issue by 282902479** [irobot-ros/ros2-performance#110]
CMake Error at CMakeLists.txt:22 (add_subdirectory):
  The source directory

    /home/humble/ros2-performance/performance_test_factory/external/json

  does not contain a CMakeLists.txt file.

**Comment by alsora** [comment]
Please follow carefully the build instructions.
https://github.com/irobot-ros/ros2-performance#build

In particular, you didn't run the following step
```
git submodule update --init --recursive
```
