### ISSUE TITLE
performance_test README_dev not found 

### ISSUE THREAD

**Issue by wudi24k** [irobot-ros/ros2-performance#130]
Could you please show how the framework is implemented and how it can be extended

**Comment by jkaniuka** [comment]
Hi @wudi24k, you can find **README_dev.md** [here](https://github.com/irobot-ros/ros2-performance/blob/a5ab85aed514448f573009a3e9d7d1d7792e589a/performances/performance_test/README_dev.md)

**Comment by wudi24k** [comment]
哈喽~~~您的邮件我已收到哦~~~谢谢哟~！祝生活愉快

**Comment by alsora** [comment]
That page is deprecated, that's why it has been removed.
The main  [README.md](https://github.com/irobot-ros/ros2-performance?tab=readme-ov-file) contains the up to date instructions on how to use and extend the framework
