### ISSUE TITLE
Question about supporting CPU affinity 

### ISSUE THREAD

**Issue by DungChau1996** [irobot-ros/ros2-performance#18]
I am new to this benchmark application. My question is that: Does it support CPU affinity? I mean the option that we can run, for example, 50 nodes on one core and others 50 nodes on second core. 

Thanks in advance and thanks for such an awesome application.

**Comment by alsora** [comment]
No, it doesn't.

However, if you provide multiple json files (each of them describing a ROS 2 system), it will start them in separate processes... Maybe you can build something on top of that

**Comment by DungChau1996** [comment]
Thanks @alsora , I will try that out :D
