### ISSUE TITLE
Foxy bug

### ISSUE THREAD

**Issue by shanpenghui** [irobot-ros/ros2-performance#74]
Hi, I find something wrong when use for Publisher/Subscriber latency. Would you consider to fix it if the bug is confirmed? Here is something wrong I found.

1. PERFORMANCE_TEST_EXAMPLES_PKG change from  performance_test to performance_test_factory in file **performances/performance_test/env.sh** line 22.

Because the app simple_pub_sub_main is in the performance_test_factory package, so it should change.

`PERFORMANCE_TEST_EXAMPLES_PKG="performance_test_factory"`

2. MSG_TYPES change from  10b to stamped10b in file **performances/performance_test/scripts/pub_sub_ros2.sh** line 18.

Because the type of msg in source file is stamped10b, maybe it had updated yet?

`MSG_TYPES=${MSG_TYPES:="stamped10b"}`

I find that in branch of foxy.

Thanks. Hope for replying.

**Comment by irobot-ros** [comment]
Hi!

Those are definitely errors, both the `env.sh` as well as most of the scripts under `performances/performance_test/scripts` are very old and not really tested/maintained.
I will put up a PR to fix them though.
Let me know if you see any other issue, or just open a PR yourself!
