### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChinmayGameti** [irobot-ros/ros2-performance#77]
Hi all,

As I was running ros2-benchmark on Linux with ros2 dashing environment, 
I use this command,
./benchmark topology/sierra_nevada.json -ipc off 
But in the JSON file, the 'msg_pass_by' is 'shared pointer', 
I want to evaluate the benchmarks for all nodes running in separate processes and also communication medium to be Sockets/UDP which is what I want to see. Is there some way to do that?

**Comment by alsora** [comment]
That option is not related with intra-process communication or with the fact that you are running in different processes.

It defines the interaction between the node and the publisher, in particular whether the node should give ownership of the message to the publisher (if the value is "unique pointer") or whether they should share ownership (if the value is "shared pointer").

Note that setting `--ipc off` will not make the system multi-process, but it will simply disable the rclcpp intra-process optimizations.
Depending on the DDS that you are using, it may still perform optimizations if you are running publisher and subscriptions in the same process.

**Comment by mauropasse** [comment]
> I want to evaluate the benchmarks for all nodes running in separate processes and also communication medium to be Sockets/UDP which is what I want to see. Is there some way to do that?

For multi-process sending messages through network interfaces you can define multiple json's files, each with the nodes/pubs/subs which will run per process.

`./irobot-benchmark node1.json node2.json node3.json -ipc off`
or run in different terminals
`./irobot-benchmark node1.json -ipc off`
`./irobot-benchmark node2.json -ipc off`
