### ISSUE TITLE
some problems about the colon

### ISSUE THREAD

**Issue by Doinbo** [irobot-ros/ros2-performance#81]
i have get a Error  Unknown Cmake command rosidl_get_typesupport_target
<img width="364" alt="github" src="https://user-images.githubusercontent.com/95084764/151414238-10838152-8411-4520-b405-06e8854d6f6e.png">

**Comment by alsora** [comment]
Hi @Doinbo, the master branch is now tracking ROS 2 rolling distribution.

Either update your environment to ROS 2 rolling or use a different branch (for example `galactic` if that's your ROS distribution).

**Comment by alsora** [comment]
@Doinbo how did you install ROS rolling? which version are you using? Have you sourced the rolling environment before building and optionally cleared the build directory if the previous build was with another distribution?

**Comment by Doinbo** [comment]
thanks for your solutions , may i ask you if this is the right result from this project?
![ros2 performance](https://user-images.githubusercontent.com/95084764/152327296-e5fea176-86df-4aa1-9029-ee5acf8880cd.png)
![performance2](https://user-images.githubusercontent.com/95084764/152327316-92fefdcf-195a-4455-a3ae-c26758ba638f.png)

**Comment by alsora** [comment]
Yes, that's the expected result when running one of the default topologies (`sierra_nevada.json`).
You can edit that topology or create new one to better represent the system you want to simulate and benchmark

**Comment by Doinbo** [comment]
may i ask one more question about the target performance with Sierra Nevada and Mont Blanc, are they both best_effect connections or just a exampel?

**Comment by alsora** [comment]
what do you mean by best_effect connections?

**Comment by Doinbo** [comment]
For a compare between prioritized connection with Best-effort connection?

**Comment by mauropasse** [comment]
`sierra_nevada.json` and `mont_blanc.json` have not specified explicitly the `qos_reliability` so they both should have `RMW_QOS_POLICY_RELIABILITY_RELIABLE` QoS reliability.
But you can set any reliability you want, check this [example](https://github.com/irobot-ros/ros2-performance/blob/master/performance_test_factory/examples/simple_architecture.json).

**Comment by Doinbo** [comment]
i have change the reliablity with this example, but i do not know how to run the json and get the performance of ros2 likebefore.
should i remove the last package? And colon the package again?
![Uploading json1.png…]()
