### ISSUE TITLE
some problem with colon (rolling)

### ISSUE THREAD

**Issue by Doinbo** [irobot-ros/ros2-performance#84]
i am so sorry to bother you again. i just can not to colon all the package . Even so the ros2 environment is rolling .
Would you mind help me to solve the problem.

![colon](https://user-images.githubusercontent.com/95084764/152144356-80fc2394-41f0-42f2-96f2-daab9854175a.png)

**Comment by alsora** [comment]
Please don't open new tickets for the same problem.
You already have https://github.com/irobot-ros/ros2-performance/issues/81 opened.
