### ISSUE TITLE
about the performance_test_factory to make a new jason

### ISSUE THREAD

**Issue by Doinbo** [irobot-ros/ros2-performance#86]

**Comment by Doinbo** [comment]
![json1](https://user-images.githubusercontent.com/95084764/152523720-336b9ee3-796d-4d21-b0bc-87f8e0d3f1bb.png)
i just do not know how to run this json file and get the result like before

**Comment by alsora** [comment]
Have a look at how to run the performance application: https://github.com/irobot-ros/ros2-performance/tree/master/irobot_benchmark#running

the `irobot_benchmark` executable takes as command line argument the path to the json file you want to run.

**Comment by Doinbo** [comment]
i do not know why,but i just can not run the performance application
![json2](https://user-images.githubusercontent.com/95084764/152525726-e730d620-0a11-45d5-9268-2b98eaba0982.png)

**Comment by Doinbo** [comment]
should i remove the package before and colon that again?

**Comment by Doinbo** [comment]
what is my (path to performances)

**Comment by alsora** [comment]
I'm sorry, but I highly suggest you to learn how to use the Linux command shell and ROS before trying to use this tool.
All your problems have nothing to do with this repository.

You clearly already built the `irobot_benchmark` application somewhere, so why are you trying to build it again?
In the documentation `cp -R <path to performances> performances_ws/src` indicates that you should copy the `ros2-performance` library and build it.
