### ISSUE TITLE
some trouble with colcon

### ISSUE THREAD

**Issue by Doinbo** [irobot-ros/ros2-performance#87]
i am sorry to bother you again ,
i remove the package and now when i restart the project 
there is also a fehler
![colon](https://user-images.githubusercontent.com/95084764/152535659-b6e54ad5-fe41-4602-84b4-8288003eef3d.png)

**Comment by alsora** [comment]
This problem has nothing to do with this repository.
It looks like your compiler `/usr/bin/cc` is corrupted.
