### ISSUE TITLE
a little problem with cmake

### ISSUE THREAD

**Issue by Doinbo** [irobot-ros/ros2-performance#88]
![image](https://user-images.githubusercontent.com/95084764/152545763-83d1c1cc-dd99-4c34-bd08-444b78f4d4b9.png)
there is a error from cmake like this

**Comment by alsora** [comment]
@Doinbo I don't want to be rude, but please try things twice before opening useless tickets.
You built the code successfully 2 days ago as you showed here https://github.com/irobot-ros/ros2-performance/issues/81#issuecomment-1028852385

any further problem is related to your environment and not to this repository

**Comment by Doinbo** [comment]
I must say sorry sincerely. I am doing a Experiment for my master Degree. But i have remove all the package. So i will check About my System and Environment by myself.
Thanks for your answers
