### ISSUE TITLE
bash env.sh

### ISSUE THREAD

**Issue by calvinyy-oss** [irobot-ros/ros2-performance#93]
thanks for your benchmark.When I try to repeat your experiments.I first run the :source env.sh. Then I get some problem:Directory /root/perf_ws/install doesn't exist.Also I wonder how to run the expriments(eg:cpu memory etc.)

**Comment by alsora** [comment]
The instructions for running the performance tests are here https://github.com/irobot-ros/ros2-performance#run
They don't require the use of any bash script.

Why are you trying to use the `env.sh` script?
I suggest you to not use the bash scripts unless you know what you are doing and how to use this application.
The instructions for using the bash scripts are here https://github.com/irobot-ros/ros2-performance/blob/master/performance_test/bash_scriptsREADME.md
The instructions clearly indicate that you need to modify some paths in the scripts before using them.

**Comment by calvinyy-oss** [comment]
> The instructions for running the performance tests are here https://github.com/irobot-ros/ros2-performance#run They don't require the use of any bash script.
> 
> Why are you trying to use the `env.sh` script? I suggest you to not use the bash scripts unless you know what you are doing and how to use this application. The instructions for using the bash scripts are here https://github.com/irobot-ros/ros2-performance/blob/master/performance_test/bash_scriptsREADME.md The instructions clearly indicate that you need to modify some paths in the scripts before using them.

because I want to follow the experiments to test the CPU latency etc.When I run the benchmark I get a lot of data but not clear as experiments.

**Comment by calvinyy-oss** [comment]
I want to have a quick test to see when there is a pub and sub,then send different size msgs, to see cpu usage latency memory,So I try to follow the experiments file .
