### ISSUE TITLE
bash scripts/pub_sub_ros2.sh

### ISSUE THREAD

**Issue by calvinyy-oss** [irobot-ros/ros2-performance#96]
![图片](https://user-images.githubusercontent.com/75769276/161733623-19afd685-7782-46df-bdba-23e465a0ccd3.png)
SORRY,I have update the bug you fixed,But there is still the same problem.I just follow the bash_scriptsREADME.md to do.

**Comment by alsora** [comment]
The problem is that `/home/calvin/performance01_ws/performance_test_factory/lib/performance_test_factory/simple_pub_sub_main` does not exist.

How did you edit `env.sh` ?
In particular I suspect that you set the wrong `ROS2_PERFORMANCE_TEST_INSTALL_PATH`

**Comment by calvinyy-oss** [comment]
Thank you.Yes,the ROS2_PERFORMANCE_TEST_INSTALL_PATH is wrong,I have changed it to ~/ros2_performance_ws/install .I try to build the package one more time.But this time I get wrong on colcon build
![图片](https://user-images.githubusercontent.com/75769276/161781199-f0b0f1a2-2830-4abf-89b1-2407716197d7.png)
Then if I source the env.sh it apears that:
![图片](https://user-images.githubusercontent.com/75769276/161781697-e0b525ae-4b96-4a27-852a-4123172fe30c.png)

**Comment by calvinyy-oss** [comment]
![图片](https://user-images.githubusercontent.com/75769276/161783652-bf3bac54-7739-45c2-8076-3273397bdcbe.png)
I find when I follow the bash_scriptsREADME.md.In the install directory,there is no performance_test_factory.Because it only populate the performance_test_msgs and performance_test package.Do I need to populate the performance_test_factory too?

**Comment by alsora** [comment]
Yesterday you were able to build successfully, so the build error has nothing to do with the code.
I suggest you to start from scratches.

**Comment by alsora** [comment]
The experiments folder is empty because all tests are failing.
I pushed a commit that should fix the problem.
Unfortunately the scripts are not tested and not used by anyone, so you may find other problems along the way.

You should pull the latest changes to the repository and try again.
If you find other errors please open a new issue
