### ISSUE TITLE
bash scripts/pub_sub_ros2.sh error

### ISSUE THREAD

**Issue by calvinyy-oss** [irobot-ros/ros2-performance#98]
![图片](https://user-images.githubusercontent.com/75769276/161798631-78ac8529-2241-4071-81bd-94d1c9a25880.png)
I have fix this bug:deleting the s.But the error is same as before.
![图片](https://user-images.githubusercontent.com/75769276/161799093-c137756d-a6d7-4147-a51c-159a962e411c.png)

**Comment by alsora** [comment]
That's strange; did you rebuild the code?

**Comment by alsora** [comment]
I updated the repository.
Try now please.

**Comment by calvinyy-oss** [comment]
Thank you! it works!
![图片](https://user-images.githubusercontent.com/75769276/161822039-9d2bfb8d-3acc-4fef-95f2-49b25e836295.png)
![图片](https://user-images.githubusercontent.com/75769276/161823677-2660500d-7ee2-40a8-9394-dbacb2055495.png)
![图片](https://user-images.githubusercontent.com/75769276/161822082-5912817a-1f55-4d51-b631-a09a656ccb86.png)
![图片](https://user-images.githubusercontent.com/75769276/161823743-b0186510-3f88-4ab3-b5c7-49c2af2ce71c.png)

And also there are some csv files.But a new problem comes out :these files are empty.

**Comment by calvinyy-oss** [comment]
![图片](https://user-images.githubusercontent.com/75769276/161824473-055d5809-1336-4ae7-9ed6-b8f8a7a0bdbf.png)
I just follow this experiment,but no data in the csv files and plot :
![图片](https://user-images.githubusercontent.com/75769276/161824645-38b48c8e-887c-4331-8bbb-7bb7c4322435.png)

**Comment by alsora** [comment]
Closing as the main purpose of the ticket as been addressed.
The fact that csv are empty is being tracked by https://github.com/irobot-ros/ros2-performance/issues/100
